routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\GuruController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\GlobalController;

Route::get('/', function () {
   return view('auth.masuk');
});


// AUTH
Route::prefix('auth')->group(function (){
    Route::get('masuk', [AuthController::class, 'index'])->name('auth.index');
    Route::post('masuk', [AuthController::class, 'store'])->name('auth.store');
    Route::get('keluar', [AuthController::class, 'logout'])->name('auth.logout');
});

// GURU
Route::prefix('guru')->group(function () {
    Route::get('home', [GuruController::class, 'index'])->name('guru.index');
    Route::get('createpoin', [GuruController::class, 'createpoin'])->name('guru.createpoin');
    Route::post('createpoin', [GuruController::class, 'storepoin'])->name('guru.storepoin');
    Route::get('lihatpoindiberi', [GuruController::class, 'lihatpoindiberi'])->name('guru.lihatpoindiberi');
    Route::get('lihatpoin', [GuruController::class, 'lihatpoin'])->name('guru.lihatpoin');
    Route::get('detailpoin', [GuruController::class, 'detailpoin'])->name('guru.detailpoin');
    Route::get('pilihkelas', [GuruController::class, 'pilihkelas'])->name('guru.pilihkelas');
    Route::get('kelas/{kelas}', [GuruController::class, 'kelas'])->name('guru.kelas');
    Route::post('carisiswa', [GuruController::class, 'carisiswa'])->name('guru.carisiswa');
    Route::patch('updatetindakan', [GuruController::class, 'updatetindakan'])->name('guru.updatetindakan');
    Route::get('multiplecreate', [GuruController::class, 'multiplecreate'])->name('guru.multiplecreate');
    Route::post('multiplecreatestore', [GuruController::class, 'multiplecreatestore'])->name('guru.multiplecreatestore');
    Route::get('pelanggaran', [GuruController::class, 'pelanggaran'])->name('guru.pelanggaran');
});

// ADMIN
Route::prefix('admin')->group(function () {
    Route::get('index', [AdminController::class, 'index'])->name('admin.index');
    // pelanggaran
    Route::get('createpelanggaran', [AdminController::class, 'createpelanggaran'])->name('admin.createpelanggaran');
    Route::post('storepelanggaran', [AdminController::class, 'storepelanggaran'])->name('admin.storepelanggaran');
    Route::get('tampilkanpelanggaran', [AdminController::class, 'tampilkanpelanggaran'])->name('admin.tampilkanpelanggaran');
    Route::get('editpelanggaran/{pelanggaran:id}', [AdminController::class, 'editpelanggaran'])->name('admin.editpelanggaran');
    Route::patch('updatepelanggaran', [AdminController::class, 'updatepelanggaran'])->name('admin.updatepelanggaran');
    Route::get('destroypelanggaran/{pelanggaran:id}', [AdminController::class, 'destroypelanggaran'])->name('admin.destroypelanggaran');
    
    // pengguna
    Route::get('createpengguna', [AdminController::class, 'createpengguna'])->name('admin.createpengguna');
    Route::post('storepengguna', [AdminController::class, 'storepengguna'])->name('admin.storepengguna');
    Route::get('tampilkanpengguna', [AdminController::class, 'tampilkanpengguna'])->name('admin.tampilkanpengguna');
    Route::get('editpengguna/{pengguna:id}', [AdminController::class, 'editpengguna'])->name('admin.editpengguna');
    Route::patch('updatepengguna', [AdminController::class, 'updatepengguna'])->name('admin.updatepengguna');
    Route::get('destroypengguna/{pengguna:id}', [AdminController::class, 'destroypengguna'])->name('admin.destroypengguna');

    // LAPORAN
    Route::get('siswaperingatan', [AdminController::class, 'siswaperingatan'])->name('admin.siswaperingatan');
    Route::get('laporan', [AdminController::class, 'laporan'])->name('admin.laporan');
    Route::get('downloadlaporansiswa/{transaksipelanggaran:siswa_id}', [AdminController::class, 'downloadlaporansiswa'])->name('admin.downloadlaporansiswa');
    Route::get('hapustransaksipoin/{transaksipelanggaran:id}', [AdminController::class, 'hapustransaksipoin'])->name('admin.hapustransaksipoin');

    
});

// SISWA
Route::prefix('siswa')->group(function () {
    Route::get('index', [SiswaController::class, 'index'])->name('siswa.index');
    Route::get('pelanggaransaya', [SiswaController::class, 'pelanggaransaya'])->name('siswa.pelanggaransaya');
    Route::get('rankingpoin', [SiswaController::class, 'rankingpoin'])->name('siswa.rankingpoin');
    Route::get('pelanggaran', [SiswaController::class, 'pelanggaran'])->name('siswa.pelanggaran');
});

// GLOBAL
Route::get('daftar', [GlobalController::class, 'daftar'])->name('global.daftar');
Route::post('daftarstore', [GlobalController::class, 'daftarstore'])->name('global.daftarstore');

app/Models/Pelanggaran.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pelanggaran extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function TransaksiPelanggaran(){
        return $this->hasMany('\App\Models\TransaksiPelanggaran');
    }

    public function getNamaPelanggaranAttribute($value){
        return ucwords($value);
    }

    public function getTindakanLangsungAttribute($value){
        return ucwords($value);
    }
}

app/Models/Siswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function Siswa(){
        return $this->hasMany('\App\Models\TransaksiPelanggaran');
    }

    public function Pengguna(){
        return $this->belongsTo('\App\Models\Pengguna');
    }

    public function Poin(){
        return $this->hasOne('\App\Models\Poin');
    }

    public function getNamaAttribute($value){
        return strtoupper($value);
    }

    public function getKelasAttribute($value){
        return strtoupper($value);
    }
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class SiswaController extends Controller
{
    public function __construct(){
        return $this->middleware('isSiswa');
    }

    public function index(Request $request){
        $pengguna = \App\Models\Pengguna::where('id', '=', $request->session()->get('id'))->first();
        $siswa = \App\Models\Siswa::where('pengguna_id', '=', $request->session()->get('id'))->first();
        $transaksiPelanggarans = \App\Models\TransaksiPelanggaran::where('siswa_id', '=', $siswa->id)->get();
        $belumDitindak = \App\Models\TransaksiPelanggaran::where('siswa_id', '=', $siswa->id)->where('status_tindakan_langsung', 0)->count();
        $sudahDitindak = \App\Models\TransaksiPelanggaran::where('siswa_id', '=', $siswa->id)->where('status_tindakan_langsung', 1)->count();

        
        return view('siswa.index', ['pengguna' => $pengguna, 'siswa' => $siswa, 'transaksiPelanggarans' => $transaksiPelanggarans, 'belumDitindak' => $belumDitindak, 'sudahDitindak' => $sudahDitindak]);
    }
    
    public function rankingpoin(){
        $poins = \App\Models\Poin::orderBy('poin', 'desc')->get();
        return view('siswa.rankingpoin', ['poins' => $poins]);
    }

    public function pelanggaransaya(Request $request){ 
        $pengguna = \App\Models\Pengguna::where('id', '=', $request->session()->get('id'))->first();
        $siswa = \App\Models\Siswa::where('pengguna_id', '=', $request->session()->get('id'))->first();
        $transaksiPelanggarans = \App\Models\TransaksiPelanggaran::with('pelanggaran')->where('siswa_id', '=', $siswa->id)->get();
        
        return view('siswa.pelanggaransaya', ['pengguna' => $pengguna, 'siswa' => $siswa, 'transaksiPelanggarans' => $transaksiPelanggarans]);
    }

    public function pelanggaran(){
        $pelanggarans = \App\Models\Pelanggaran::orderBy('jumlah_poin', 'DESC')->get();
        
        return view('siswa.pelanggaran', ['pelanggarans' => $pelanggarans]);
    }
}

resources/views/siswa/index.blade.php
@extends('master.master-siswa')

@section('back')

@section('judul')

Hai, {{$pengguna->siswa->nama}}!

{{-- <small> {{$pengguna->siswa->kelas}} </small> --}}

@endsection

@section('konten')



    <div class="row p-4 bg-warning" style="margin-top: 15%; border-radius: 10px; border-top-left-radius: 20px; border-bottom-right-radius: 20px;background-image: url('/img/global/wave.svg'); background-repeat: no-repeat; background-size: cover;">

        <div class="col-2">

            <img src="/img/global/level.svg" alt="" height="30px;">

        </div>

        <div class="col">

            <ceter>

            <span style="font-size: px;"> Level  </span> <br>

            <span style="font-size: 25px;">

                @if (is_null($siswa->poin))

                

                @elseif ($siswa->poin->poin == 0)

                    Anak Baik

                @elseif ($siswa->poin->poin >=1 and  $siswa->poin->poin <= 99)

                    Siswa Nakal

                @elseif ($siswa->poin->poin >=100 and  $siswa->poin->poin <= 499)

                Luar biasa nakal

                @elseif ($siswa->poin->poin >=500 and  $siswa->poin->poin <= 999)

                Siap-siap DO

                @elseif ($siswa->poin->poin >= 1000)

                Sudah DO

                @else
                Masih aman
                @endif

            </span>

            </center>

        </div>

    </div>



    <div class="row p-3">

        <div class="col">

            <div class="row text-light">

                <div class="col mr-1 shadow bg-danger border p-3" style="text-align: center; border-radius: 10px;background-image: url('/img/global/wave1.svg'); background-repeat: no-repeat; background-size: cover;" >

                    <span></span> <br>

                    <span style="font-size: 3rem; font-weight: bold;">

                        @if (is_null($siswa->poin))
                            0
                        @elseif ($siswa->poin->poin >= 0)

                            {{$siswa->poin->poin}}

                        @else
                            0
                        @endif

                    </span> <br>

                    <span>Poin</span>

                </div>

                <div class="col ml-1 shadow bg-info border p-3" style="text-align: center; border-radius: 10px;background-image: url('/img/global/wave2.svg'); background-repeat: no-repeat; background-size: cover;" >

                    <span></span> <br>

                    <span style="font-size: 3rem; font-weight: bold;">

                        @if (is_null($transaksiPelanggarans))

                            0

                        @elseif ($transaksiPelanggarans->count() >= 0)

                            {{$transaksiPelanggarans->count()}}

                        @endif

                    </span> <br>

                    <span>Pelanggaran</span>

                </div>

            </div>



            <div class="row mt-1 text-light">

                <div class="col mr-1 shadow bg-warning border p-3" style="text-align: center; border-radius: 10px;background-image: url('/img/global/wave3.svg'); background-repeat: no-repeat; background-size: cover;" >

                    <span></span> <br>

                    <span style="font-size: 3rem; font-weight: bold;">

                        @if (is_null($belumDitindak))

                            0

                        @elseif ($belumDitindak >= 0)

                            {{$belumDitindak}}

                        @endif

                    </span> <br>

                    <span>Belum dilakukan</span>

                </div>

                <div class="col ml-1 shadow bg-primary border p-3" style="text-align: center; border-radius: 10px;background-image: url('/img/global/wave4.svg'); background-repeat: no-repeat; background-size: cover;" >

                    <span></span> <br>

                    <span style="font-size: 3rem; font-weight: bold;">

                        @if (is_null($sudahDitindak))

                            0

                        @elseif ($sudahDitindak >= 0)

                            {{$sudahDitindak}}

                        @endif

                    </span> <br>

                    <span>Sudah dilakukan</span>

                </div>

            </div>

        </div>

    </div>




    <div class="row mt-1 p-3" data-aos="flip-up" style="background-color: #FFFFFF; border-radius: 10px;">

        <div class="col-2 p-2" style="background-color: #D9D9D9; border-radius: 10px;">

            <center> <img style="height: 30px;" src="/img/global/list.svg" alt=""> </center>

        </div>  

        <div class="col">

            <button style="width: 100%; text-align: left;">

                <a href="{{route('siswa.pelanggaran')}}"> Detail Pelanggaran</a>

            </button>

        </div>

    </div>

    <div class="row mt-3 p-3" data-aos="flip-up" style="background-color: #FFFFFF; border-radius: 10px;">

        <div class="col-2 p-2" style="background-color: #D9D9D9; border-radius: 10px;">

            <center> <img style="height: 30px;" src="/img/global/list.svg" alt=""> </center>

        </div>

        <div class="col">

            <button style="width: 100%; text-align: left;">

                <a href="{{route('siswa.pelanggaransaya')}}"> Pelanggaran Saya</a>

            </button>

        </div>

    </div>

    <div class="row mt-3 p-3" data-aos="flip-up" style="background-color: #FFFFFF; border-radius: 10px;">

        <div class="col-2 p-2" style="background-color: #D9D9D9; border-radius: 10px;">

            <center> <img style="height: 30px;" src="/img/global/list.svg" alt=""> </center>

        </div>

        <div class="col">

            <button style="width: 100%; text-align: left;">

                <a href="{{route('siswa.rankingpoin')}}"> Ranking Poin</a>

            </button>

        </div>

    </div>



@endsection

resources/views/siswa/pelanggaran.blade.php
@extends('master.master-siswa')

@section('back')   
<a href="{{route('siswa.index')}}">
   <center><img src="/img/global/back.svg" alt=""></center>
</a>
@endsection
@section('judul')
   Semua Pelanggaran
@endsection

@section('konten')

<div class="container bg-light" style="margin-top: 50px; border-radius: 10px;">
<div class="row p-1 pt-2">
    <div class="col-2 mr-1 p-2" style="border-radius: 10px; background-color: #00425A; color: white;"><center> No. </center></div>
    <div class="col mr-1 p-2" style="border-radius: 10px; background-color: #00425A; color: white;"><center> Nama </center></div>
</div>
@foreach ($pelanggarans as $pelanggaran )
    <div class="row p-1">
        <div class="col-2 mr-1 p-2" style="border-radius: 10px; background-color: #F8F4EA;">
            <center>{{$loop->iteration}}.</center>
        </div>
        <div class="col mr-1 p-2" style="border-radius: 10px; background-color: #F8F4EA;">
            <b> {{$pelanggaran->nama_pelanggaran}} </b> <br>
            <small> {{$pelanggaran->tindakan_langsung}} </small> <br>

            <small class="text-danger"> {{$pelanggaran->jumlah_poin}} Poin </small>
        </div>
    </div>
@endforeach
</div>

@endsection

resources/views/siswa/pelanggaransaya.blade.php
@extends('master.master-siswa')
@section('back')
<center>
<a href="{{route('siswa.index')}}">
    <img src="/img/back.png" alt="">
</a>
</center>
@endsection
@section('judul','Pelanggaran Saya')
@section('konten')


    <div class="row" style="margin-top: 10%;">
        <div class="col p-3 rounded border">
            <table class="table text-secondary">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Pelanggaran</th>
                        <th>Poin</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($transaksiPelanggarans as $transaksiPelanggaran)
                        <tr class="{{$transaksiPelanggaran->status_tindakan_langsung == "0" ? "text-danger" : "text-dark"}}" data-toggle="collapse" data-target="#{{$transaksiPelanggaran->id}}" aria-expanded="false">
                            <td>{{$loop->iteration}}.</td>
                            <td> {{$transaksiPelanggaran->pelanggaran->nama_pelanggaran}} </td>
                            <td> {{$transaksiPelanggaran->pelanggaran->jumlah_poin}}  </td>
                        </tr>
                        <tr class="collapse bg-secondary text-light" id="{{$transaksiPelanggaran->id}}">
                            <td colspan="4">
                                {{ $transaksiPelanggaran->created_at != null ? date_format($transaksiPelanggaran->created_at,"d M Y H:i:s") : "-"}} <br>
                                @if ($transaksiPelanggaran->status_tindakan_langsung == "0")                                
                                   <b class="text-warning">{{$transaksiPelanggaran->pelanggaran->tindakan_langsung}} </b>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

    

@endsection

resources/views/siswa/rankingpoin.blade.php
@extends('master.master-siswa')
@section('back')
<center>
<a href="{{route('siswa.index')}}">
    <img src="/img/back.png" alt="">
</a>
</center>
@endsection
@section('judul','Ranking Poin Siswa')

@section('konten')

<div class="container-fluid p-0"  style="margin-top: 40px; border-radius: 10px;">
    <div class="row" style="background-color: #00425A; color: white; border-radius: 10px;">
        <div class="col p-2"><center> Nama </center></div>
        <div class="col p-2"><center>Kelas</center></div>
        <div class="col-2 p-2"><center>Poin</div>
    </div>
@foreach ($poins as $poin)
<div class="row p-2 border" style="background-color: white; border-radius: 10px;">
    <div class="col p-2">
        {{$poin->siswa->nama}}
    </div>
    <div class="col p-2">        
        <center>{{$poin->siswa->kelas}}</center>
    </div>
    <div class="col-2 p-2">
       <center> {{$poin->poin}} </center>
    </div>
</div>
@endforeach

@endsection